export enum MedicalRecordStatusType {
  REQUEST_SENT = 'REQUEST_SENT',
  CONFIRMED_VET = 'CONFIRMED_VET',
  REJECTED_VET = 'REJECTED_VET',
  REJECTED_CLIENT= 'REJECTED_CLIENT',
  DONE = 'DONE',
  RESERVED = 'RESERVED'
}