export enum MedicalRecordStatusType {
  REQUEST_SENT = 'REQUEST_SENT',
  DELIVERED = 'DELIVERED',
  CONFIRMED = 'CONFIRMED',
  REJECTED_VET = 'REJECTED_VET',
  REJECTED_CLIENT= 'REJECTED_CLIENT',
  DONE = 'DONE',
  RESERVED = 'RESERVED'
}
