export enum ServiceType {
    PREVENTIVNA_NEGA = 'PREVENTIVNA_NEGA',
    OPERACIJE = 'OPERACIJE', 
    NEGA_ZUBA = 'NEGA_ZUBA', 
    VAKCINACIJA = 'VAKCINACIJA', 
    UKLANJANJE_PARAZITA = 'UKLANJANJE_PARAZITA',
    HITAN_SLUCAJ = 'HITAN_SLUCAJ'
}